### ISSUE TITLE
如何使用factory

### ISSUE THREAD

**Issue by a631069724** [jukylin/esim#7]
有没有具体的示例
初始化结构体

Usage:
  esim factory [flags]

Flags:
  -h, --help           help for factory
  -n, --new            with new
      --oc             generate conf option
      --ol             generate logger option
  -o, --option         New with option
      --print          print to terminal
      --sdir string    struct path
      --sname string   struct name
  -s, --sort           sort the field (default true)

Global Flags:
      --config string       config file (default is $HOME/.esim.yaml)
      --infra_dir string    Infra dir (default "internal/infra/")
      --infra_file string   Infra file name (default "infra.go")
      --inject              Automatic inject instance to infra (default true)
      --star                With star

**Comment by jukylin** [comment]
进入到要初始化的结构体目录下：esim factory --sname struct_name -n -o

**Comment by a631069724** [comment]
有没有项目示例参考一下，如果esim db2entity支持oracle数据库就太好了。

**Comment by jukylin** [comment]
esim factory 只是生成一些初始化代码，你随便找个结构体就可以尝试。
oracle我找时间看看。

**Comment by a631069724** [comment]
thanks
